spin_manifest_version = 2

[application]
name = "webfinger"
version = "0.0.1"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "webfinger"

[component.webfinger]
source = "target/wasm32-wasip1/release/webfinger.wasm"
allowed_outbound_hosts = []
[component.webfinger.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
